# Home Assistant Plugin Configuration
homeassistant:
  # Home Assistant Instance Configuration
  host: "${HA_HOST:localhost}"
  port: "${HA_PORT:8123}"
  token: "${HA_TOKEN:configure_your_token_in_a_secret_or_external_env}"  # Long-lived access token
  ssl: "${HA_SSL:false}"
  
  # Connection Settings
  timeout: 30
  verify_ssl: true
  
  # Command Settings
  command_prefix: "ha"
  admin_only: false
  
  # Entity Categories to expose via commands
  entities:
    lights: true
    switches: true
    sensors: true
    automation: true
    climate: true
    cover: true
    fan: true
    lock: true
    media_player: true
    vacuum: true
  
  # Security Settings
  allowed_domains:
    - light
    - switch
    - automation
    - climate
    - cover
    - fan
    - lock
    - media_player
    - vacuum
  
  # Response Settings
  max_entities_per_response: 90
  include_state_attributes: false